name: Fineract Docker build - Type-Safe project

on:
  push:
    branches:
      - FINERACT-2021/refactor_GET_Methods

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Set up NodeJs 16
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 16
      - name: Congfigure vega-cli
        run: npm i -g vega-cli --unsafe
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@216d1ad2b3710bf005dc39237337b9673fd8fcd5
      - name: Install additional software
        run: |
          sudo apt-get update
          sudo apt-get install ghostscript graphviz -y
      - name: Build Fineract
        run: ./gradlew --no-daemon --console=plain clean build -x test -x cucumber -x check

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          # registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Fineract base image
        run: ./gradlew --no-daemon --console=plain :custom:docker:dockerPushImage -x test -x cucumber -x check

      - name: Build and push Fineract custom image
        run: ./gradlew --no-daemon --console=plain :custom:docker:jib -x test -x cucumber -x check
